# pytest.ini
[pytest]
addopts = -sv
python_files = test_*.py *_test.py

# Регистрируем кастомные маркировки
markers =
    ui: Маркировка для ГШ тестов.
    slow: Маркировка для медленных тестов.
    critical: Маркировка для критичных тестов.
    regression: Маркировка для регрессионных тестов.
    smoke: Смоук-тест.
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    authorization: Маркировка для тестов, связанных с авторизацией пользователей.
    courses: Маркировка для тестов, связанных с разделом курсов.
    dashboard: Маркировка для тестов, связанных с рабочей панелью.