# pytest.ini
[pytest]
python_files = test_*.py *_test.py
pytest_classes = Test*
pytest_functions = test_*
# Регистрируем кастомные маркировки
markers =
    ui: Маркировка для ГШ тестов.
    slow: Маркировка для медленных тестов.
    critical: Маркировка для критичных тестов.
    regression: Маркировка для регрессионных тестов.
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    authorization: Маркировка для тестов, связанных с авторизацией пользователей.
    courses: Маркировка для тестов, связанных с разделом курсов.